// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk9lf0syKFZ2Lut5PrGukMc4SOiII3_IQ',
    appId: '1:29786346812:web:185a696b7bf8b25b7a3a39',
    messagingSenderId: '29786346812',
    projectId: 'connect-108cd',
    authDomain: 'connect-108cd.firebaseapp.com',
    storageBucket: 'connect-108cd.firebasestorage.app',
    measurementId: 'G-73PQBKMYDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Rbyy5oT4rul5ZblOGQhEZgl1GXa__zI',
    appId: '1:29786346812:android:cf1d473b02e172337a3a39',
    messagingSenderId: '29786346812',
    projectId: 'connect-108cd',
    storageBucket: 'connect-108cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrT9TYQeTOXYZaCAOH4SzG7XkPq0Gb8hw',
    appId: '1:29786346812:ios:01d64e19eec97c5e7a3a39',
    messagingSenderId: '29786346812',
    projectId: 'connect-108cd',
    storageBucket: 'connect-108cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrT9TYQeTOXYZaCAOH4SzG7XkPq0Gb8hw',
    appId: '1:29786346812:ios:01d64e19eec97c5e7a3a39',
    messagingSenderId: '29786346812',
    projectId: 'connect-108cd',
    storageBucket: 'connect-108cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk9lf0syKFZ2Lut5PrGukMc4SOiII3_IQ',
    appId: '1:29786346812:web:3194ac708612182a7a3a39',
    messagingSenderId: '29786346812',
    projectId: 'connect-108cd',
    authDomain: 'connect-108cd.firebaseapp.com',
    storageBucket: 'connect-108cd.firebasestorage.app',
    measurementId: 'G-3P655K49GG',
  );
}
